schedules:
  adhoc:
    schedule: adhoc
    notify:
      slack: cpp-driver-dev-bots
  commit:
    schedule: per_commit
    notify:
      slack: cpp-driver-dev-bots
    branches:
      include: ["/CPP-\\d+/", "master"]
architecture:
  - x64
os:
  - ubuntu/bionic64/cpp
  - ubuntu/trusty64/cpp
  - ubuntu/xenial64
  - centos/6-64
  - centos/7-64
env:
  LIBUV_VERSION: 1.23.0
build:
  - script: |
      . ./cpp-driver/.build.sh
      configure_environment
      install_dependencies

      build_driver 'DSE'

      FUNCTIONS+=($(grep -Eoh '(^cass_\s*(\w+)\s*\()|(^dse_\s*(\w+)\s*\()' include/dse.h | awk -F '(' '{print $1}'));
      FUNCTIONS+=($(grep -Eoh '^cass_\s*(\w+)\s*\(' cpp-driver/include/cassandra.h | awk -F '(' '{print $1}'))
      check_driver_exports 'build/libdse_static.a' "${FUNCTIONS[@]}"

      build/cassandra-unit-tests --gtest_output=xml:cassandra-unit-test-results.xml
      build/dse-unit-tests --gtest_output=xml:dse-unit-test-results.xml

      install_driver
      test_installed_driver 'dse'

  - xunit:
    - "*unit-test-results.xml"
package:
  include: # list of files and glob paths to include in the artifact, relative to the current working directory
    - packaging/packages/*
release:
  after:
    each:
      - script: |
          . ./cpp-driver/.build.sh
          DRIVER_VERSION=$(get_driver_version 'include/dse.h' 'DSE')
          # Uploading driver packages
          curl -$ARTIFACTORY_CREDS -T "{$(echo packaging/packages/dse-cpp-driver* | tr ' ' ',')}" "https://datastax.jfrog.io/datastax/cpp-php-drivers/cpp-dse-driver/builds/$version/$SHA/$DISTRO/$RELEASE/dse/v$DRIVER_VERSION/"
          # Uploading libuv packages
          curl -$ARTIFACTORY_CREDS -T "{$(echo packaging/packages/libuv* | tr ' ' ',')}" "https://datastax.jfrog.io/datastax/cpp-php-drivers/cpp-dse-driver/builds/$version/$SHA/$DISTRO/$RELEASE/dependencies/libuv/v$LIBUV_VERSION/"
